(
SELECT
	Contratante.WPessoa_Id 	AS COD_RESPONSAVEL_EXT,
	WPessoa.Nome			AS NOM_RESPONSAVEL,
	'F'						AS IND_TPO_PESSOA,
	WPessoa.CPF 			AS NUM_CPF_CNPJ,
	DECODE(Contratante.ContratanteTi_Id,139700000000001,1,139700000000002,2,139700000000003,10)		AS COD_GRAU_PARENTESCO
FROM
	Contratante join WPessoa on Contratante.WPessoa_Id = WPessoa.Id
)
union
(
SELECT
	WPESSOA.ID 	    AS COD_RESPONSAVEL_EXT,
	WPESSOA.NOME        AS NOM_RESPONSAVEL,
	'F'					AS IND_TPO_PESSOA,
	WPESSOA.CPF			AS NUM_CPF_CNPJ,
	10					AS COD_GRAU_PARENTESCO
FROM
	MATRIC JOIN	WPESSOA ON MATRIC.WPESSOA_ID = WPESSOA.ID
WHERE
	NOT EXISTS (SELECT MATRIC_ID FROM CONTRATANTE WHERE MATRIC_ID = MATRIC.ID)
GROUP BY WPESSOA.ID,WPESSOA.NOME,WPESSOA.CPF
)
