SELECT 
	COD_PERIODO_LETIVO_EXT || COD_CURSO_EXT || COD_CAMPUS_EXT || COD_TURNO_EXT || SUBSTR(COD_HABILITACAO_EXT,1,4) || TRIM(NUM_PARCELA)||COD_PERIODO AS COD_PLANO_PARC_EXT,
	COD_PERIODO_LETIVO_EXT || COD_CURSO_EXT || COD_CAMPUS_EXT || COD_TURNO_EXT || SUBSTR(COD_HABILITACAO_EXT,1,4)||COD_PERIODO AS COD_PLANO_EXT,
	IND_DEFAULT,
  	IDT_MORA,
	PER_MORA,
	IDT_CALC_MORA,
	IDT_MULTA,
	PER_MULTA,
	IDT_CALC_MULTA,
	IDT_CORRECAO,
	PER_CORRECAO,
	IDT_CALC_CORRECAO,
	NUM_PARCELA,
	VAL_TAXA_PARCELAMENTO  
FROM 
((
SELECT
	CURROFE.PLETIVO_ID 							AS COD_PERIODO_LETIVO_EXT,
	CURSO.ID 									AS COD_CURSO_EXT,
	CURSO.CODIGO||' '||RECCURSO.HABILITACAO  	AS COD_HABILITACAO_EXT,
	CURROFE.CAMPUS_ID							AS COD_CAMPUS_EXT,
	CURROFE.PERIODO_ID							AS COD_TURNO_EXT,
	DURACXCI.SEQUENCIA							AS COD_PERIODO,
	'S' 										AS IND_DEFAULT,
	'D'											AS IDT_MORA,
	0.0003334                                   AS PER_MORA,
	'S'											AS IDT_CALC_MORA,
	'M'											AS IDT_MULTA,
	0.02										AS PER_MULTA,
	'S' 										AS IDT_CALC_MULTA,
	'N'											AS IDT_CORRECAO,
	0											AS PER_CORRECAO,
	null 										AS IDT_CALC_CORRECAO,
	TO_CHAR(PAGTOP.PARCELA,'00')				AS NUM_PARCELA,
	0	 										AS VAL_TAXA_PARCELAMENTO  
FROM
    PAGTOP,
	PAGTOUSO,
  	PAGTO,
	CURROFE,
	CURR,
	CURSO,
	RECCURSO,
    CURRXDISC,
    DURACXCI
WHERE
	CURRXDISC.DURACXCI_ID = DURACXCI.ID
AND
	CURRXDISC.CURR_ID = CURR.ID
AND
	PAGTO.ID = PAGTOP.PAGTO_ID
AND
	RECCURSO.HABILITACAO IS NOT NULL
AND
	RECCURSO.VIGENTE = 'on'
AND
	RECCURSO.CAMPUS_ID = CURROFE.CAMPUS_ID
AND
	CURSO.ID = RECCURSO.CURSO_ID
AND
	CURR.CURSO_MIG_ID = CURSO.ID
AND
	CURROFE.CURR_ID = CURR.ID
AND
	PAGTOUSO.CURROFE_ID = CURROFE.ID
AND
	PAGTOUSO.PAGTO_ID = PAGTO.ID
AND
	PAGTOUSO.CURROFE_ID IS NOT NULL
AND
  PAGTO.RESERVAVAGA IS NULL
)
UNION
(
SELECT
	CURROFE.PLETIVO_ID 																				AS COD_PERIODO_LETIVO_EXT,
	CURSO.ID 																						AS COD_CURSO_EXT,
	CURSO.CODIGO||' '||DECODE(CURSO.CODIGO,'4003','Sequencial','4017','Sequencial',MODALIDADE.NOME) AS COD_HABILITACAO_EXT,
	CURROFE.CAMPUS_ID																				AS COD_CAMPUS_EXT,
	CURROFE.PERIODO_ID																				AS COD_TURNO_EXT,
	DURACXCI.SEQUENCIA 																				AS COD_PERIODO,
	'S' 																							AS IND_DEFAULT,
	'D'																								AS IDT_MORA,
	0.0003334                                   													AS PER_MORA,
	'S'																								AS IDT_CALC_MORA,
	'M'																								AS IDT_MULTA,
	0.02																							AS PER_MULTA,
	'S' 																							AS IDT_CALC_MULTA,
	'N'																								AS IDT_CORRECAO,
	0																								AS PER_CORRECAO,
	null 																							AS IDT_CALC_CORRECAO,
	TO_CHAR(PAGTOP.PARCELA,'00')																	AS NUM_PARCELA,
	0	 																							AS VAL_TAXA_PARCELAMENTO  
FROM
	PAGTOP,
	PAGTOUSO,
  	PAGTO,
	CURROFE,
	CURR,
	CURSO,
	RECCURSO,
  	MODALIDADE,
    CURRXDISC,
    DURACXCI
WHERE
	CURRXDISC.DURACXCI_ID = DURACXCI.ID
AND
	CURRXDISC.CURR_ID = CURR.ID
AND
	PAGTO.ID = PAGTOP.PAGTO_ID
AND
	RECCURSO.MODALIDADE_ID=MODALIDADE.ID(+)
AND
	RECCURSO.HABILITACAO IS NULL
AND
	RECCURSO.VIGENTE = 'on'
AND
	RECCURSO.CAMPUS_ID = CURROFE.CAMPUS_ID
AND
	CURSO.ID = RECCURSO.CURSO_ID
AND
	CURR.CURSO_MIG_ID = CURSO.ID
AND
	CURROFE.CURR_ID = CURR.ID
AND
	PAGTOUSO.CURROFE_ID = CURROFE.ID
AND
	PAGTOUSO.PAGTO_ID = PAGTO.ID
AND
	PAGTOUSO.CURROFE_ID IS NOT NULL
AND
	PAGTO.RESERVAVAGA IS NULL  
) ) TABELA
GROUP BY 
	COD_PERIODO_LETIVO_EXT,COD_CURSO_EXT,COD_HABILITACAO_EXT,COD_CAMPUS_EXT,COD_TURNO_EXT,IND_DEFAULT,IDT_MORA,PER_MORA,IDT_CALC_MORA,IDT_MULTA,PER_MULTA,IDT_CALC_MULTA,IDT_CORRECAO,PER_CORRECAO,IDT_CALC_CORRECAO,NUM_PARCELA,VAL_TAXA_PARCELAMENTO,COD_PERIODO  
ORDER BY 1,2,3,4,5,NUM_PARCELA 