  SELECT 
     COD_PERIODO_LETIVO_EXT || COD_CURSO_EXT || COD_CAMPUS_EXT || COD_TURNO_EXT || SUBSTR(COD_HABILITACAO_EXT,1,4)||NUM_PERIODO AS COD_PLANO_EXT, TABELA.* FROM 
  ((
  SELECT
    CURROFE.PLETIVO_ID 							AS COD_PERIODO_LETIVO_EXT,
    CURSO.ID 									AS COD_CURSO_EXT,
    CURSO.CODIGO||' '||RECCURSO.HABILITACAO  	AS COD_HABILITACAO_EXT,
    CURROFE.CAMPUS_ID							AS COD_CAMPUS_EXT,
    CURROFE.PERIODO_ID							AS COD_TURNO_EXT,
    DURACXCI.SEQUENCIA 							AS NUM_PERIODO,
    PAGTO.PARCELAS 								AS NUM_PARCELA,
    'V' 										AS IDT_TPO_COBRANCA,
    Pagto_gnValor(Pagto.Id,null)*PAGTO.PARCELAS	AS VAL_PLANO_PAGAMENTO,
    NULL 										AS NUM_CREDITO,
    NULL 										AS VAL_CREDITO,
    NULL 										AS VAL_MATRICULA,
    trunc(pagto.dt)   as data1
  FROM
    PAGTOUSO,
      PAGTO,
    CURROFE,
    CURR,
    CURRXDISC,
    DURACXCI,
    CURSO,
    RECCURSO
  WHERE
    CURRXDISC.DURACXCI_ID = DURACXCI.ID
  AND
    CURRXDISC.CURR_ID = CURR.ID     
  AND
    RECCURSO.HABILITACAO IS NOT NULL
  AND
    RECCURSO.VIGENTE = 'on'
  AND
    RECCURSO.CAMPUS_ID = CURROFE.CAMPUS_ID
  AND
    CURSO.ID = RECCURSO.CURSO_ID
  AND
    CURR.CURSO_MIG_ID = CURSO.ID
  AND
    CURROFE.CURR_ID = CURR.ID
  AND
    PAGTOUSO.CURROFE_ID = CURROFE.ID
  AND
    PAGTOUSO.PAGTO_ID = PAGTO.ID
  AND
    PAGTOUSO.CURROFE_ID IS NOT NULL
  AND
    PAGTO.RESERVAVAGA IS NULL
  )
  UNION
  (
  SELECT
    CURROFE.PLETIVO_ID 																				AS COD_PERIODO_LETIVO_EXT,
    CURSO.ID 																						AS COD_CURSO_EXT,
    CURSO.CODIGO||' '||DECODE(CURSO.CODIGO,'4003','Sequencial','4017','Sequencial',MODALIDADE.NOME) AS COD_HABILITACAO_EXT,
    CURROFE.CAMPUS_ID																				AS COD_CAMPUS_EXT,
    CURROFE.PERIODO_ID																				AS COD_TURNO_EXT,
    DURACXCI.SEQUENCIA 																				AS NUM_PERIODO,
    PAGTO.PARCELAS 																					AS NUM_PARCELA,
    'V' 																							AS IDT_TPO_COBRANCA,
    Pagto_gnValor(Pagto.Id,null)*PAGTO.PARCELAS														AS VAL_PLANO_PAGAMENTO,
    NULL 																							AS NUM_CREDITO,
    NULL 																							AS VAL_CREDITO,
    NULL 																							AS VAL_MATRICULA,
    trunc(pagto.dt)   as data1
  FROM
    PAGTOUSO,
      PAGTO,
    CURRXDISC,
    CURR,
    CURROFE,
    DURACXCI,
    CURSO,
    RECCURSO,
    MODALIDADE
  WHERE
    CURRXDISC.DURACXCI_ID = DURACXCI.ID
  AND
    CURRXDISC.CURR_ID = CURR.ID     
  AND
     RECCURSO.MODALIDADE_ID=MODALIDADE.ID(+)
  AND
    RECCURSO.HABILITACAO IS NULL
  AND
    RECCURSO.VIGENTE = 'on'
  AND
    RECCURSO.CAMPUS_ID = CURROFE.CAMPUS_ID
  AND
    CURSO.ID = RECCURSO.CURSO_ID
  AND
    CURR.CURSO_MIG_ID = CURSO.ID
  AND
    CURROFE.CURR_ID = CURR.ID
  AND
    PAGTOUSO.CURROFE_ID = CURROFE.ID
  AND
    PAGTOUSO.PAGTO_ID = PAGTO.ID
  AND
    PAGTOUSO.CURROFE_ID IS NOT NULL
  AND
    PAGTO.RESERVAVAGA IS NULL  
  ) ) TABELA
  GROUP BY COD_PERIODO_LETIVO_EXT,COD_CURSO_EXT,COD_HABILITACAO_EXT,COD_CAMPUS_EXT,COD_TURNO_EXT,
  NUM_PERIODO,NUM_PARCELA,IDT_TPO_COBRANCA,VAL_PLANO_PAGAMENTO,NUM_CREDITO,VAL_CREDITO,VAL_MATRICULA,data1,NUM_PERIODO
  ORDER BY 1,2,7
   