SELECT 
  	CCORRENTE.iD 		as COD_CONVENIO_BANC_EXT, 
  	BANCO.NUMERO 		as NUM_BANCO,
  	BANCO.NOME 			as NOM_BANCO,
  	'N' 				as IND_BANCO_INTERNO,
  	CCORRENTE.AGENCIA 	as NUM_AGENCIA,
  	'0' 				as NUM_DIGITO_AGENCIA,
  	CCORRENTE.NUMERO 	as NUM_CONTA,
  	nvl(CCORRENTE.DIGITOCC,0)	as NUM_DIGITO_CONTA,
  	nvl(CCORRENTE.CONVENIO,0) 	as NUM_CONVENIO,
  	'CSR' 				as NUM_CARTEIRA, 
  	CASE
	WHEN  CCORRENTE.ID = 54500000000635 THEN
		'1'
	ELSE
		'0'
	END as NUM_INICIAL, 
  	CASE
	WHEN  CCORRENTE.ID = 54500000000635 THEN
		(select trim(to_char(substr(max(REMESSA.ID),13),'000')) from REMESSA)
	ELSE
		'0'
	END as NUM_FINAL,  
  	(select max(ID) from BOLETO where CCORRENTE_ID=CCORRENTE.ID) as NUM_ULT_BOLETA,
    'N' 				as IND_REGISTRO
FROM 
	CCORRENTE inner join BANCO on CCORRENTE.BANCO_ID = BANCO.ID  
WHERE 
	CCORRENTE.ID in (select distinct(CCORRENTE_ID) from BOLETO)
	