SELECT
	NULL AS COD_LANC_PLANO_EXT,
	NULL AS COD_PLANO_EXT,
	NULL AS COD_PERIODO_LETIVO_EXT,
	NULL AS COD_CURSO_EXT,
	NULL AS COD_HABILITACAO_EXT,
	NULL AS COD_CAMPUS_EXT,
	NULL AS COD_TURNO_EXT,
	NULL AS NUM_PERIODO,
	NULL AS COD_LANCAMENTO_EXT,
	NULL AS VAL_LANCAMENTO,
	NULL AS IND_CONDICIONADO_VENC
FROM
	
WHERE
