SELECT
	COD_ALUNO_EXT,
	COD_PERIODO_LETIVO_EXT || COD_CURSO_EXT || COD_CAMPUS_EXT || COD_TURNO_EXT || SUBSTR(COD_HABILITACAO_EXT,1,4)||NUM_PERIODO AS COD_PLANO_EXT,
	COD_PERIODO_LETIVO_EXT,
	COD_CURSO_EXT,
	COD_HABILITACAO_EXT,
	COD_CAMPUS_EXT,
	COD_TURNO_EXT,  
	NUM_PERIODO,
	COD_RESPONSAVEL_EXT,
	IDT_TPO_RESP,
	VAL_RESPONSABILIDADE,
	NUM_PARCELA_INI,
	NUM_PARCELA_FIM  
from
(
(
SELECT
	Matric_gsCodAlunoExt(MATRIC.ID) 			AS COD_ALUNO_EXT,
	CURROFE.PLETIVO_ID 							AS COD_PERIODO_LETIVO_EXT,
	CURSO.ID 									AS COD_CURSO_EXT,
	CURSO.CODIGO||' '||RECCURSO.HABILITACAO  	AS COD_HABILITACAO_EXT,
	CURROFE.CAMPUS_ID 							AS COD_CAMPUS_EXT,
	CURROFE.PERIODO_ID 							AS COD_TURNO_EXT,
	DURACXCI.SEQUENCIA 							AS NUM_PERIODO,
	CONTRATANTE.ID  							AS COD_RESPONSAVEL_EXT,
	'PRC' 										AS IDT_TPO_RESP,
	100 										AS VAL_RESPONSABILIDADE,
  	TO_CHAR(INICIO,'MM')          				AS NUM_PARCELA_INI,
  	TO_CHAR(FINAL,'MM')          				AS NUM_PARCELA_FIM
FROM
  	CONTRATANTE,
  	MATRIC,
  	TURMAOFE,
  	TURMA,
  	DURACXCI,
  	CURROFE,
  	CURR,
  	CURSO,
  	RECCURSO,
    PLETIVO
where  
    CURROFE.PLETIVO_ID = PLETIVO.ID
AND
  	MATRIC.STATE_ID > 3000000002001
AND
  	RECCURSO.CAMPUS_ID = CURROFE.CAMPUS_ID
AND
  	RECCURSO.VIGENTE = 'on'  
AND
  	RECCURSO.HABILITACAO IS NOT NULL  
AND
  	CURSO.ID = RECCURSO.CURSO_ID
AND
  	TURMA.DURACXCI_ID = DURACXCI.ID
AND
  	TURMAOFE.TURMA_ID = TURMA.ID
AND
  	CONTRATANTE.MATRIC_ID = MATRIC.ID
and
  	MATRIC.TURMAOFE_ID = TURMAOFE.ID
AND
  	TURMAOFE.CURROFE_ID = CURROFE.ID
AND
  	CURROFE.CURR_ID = CURR.ID
AND
  	CURR.CURSO_ID = CURSO.ID
)
UNION
(
SELECT
	Matric_gsCodAlunoExt(MATRIC.ID) 	AS COD_ALUNO_EXT,
	CURROFE.PLETIVO_ID 					AS COD_PERIODO_LETIVO_EXT,
	CURSO.ID 							AS COD_CURSO_EXT,
	CURSO.CODIGO||' '||DECODE(CURSO.CODIGO,'4003','Sequencial','4017','Sequencial',MODALIDADE.NOME) AS COD_HABILITACAO_EXT,
	CURROFE.CAMPUS_ID 					AS COD_CAMPUS_EXT,
	CURROFE.PERIODO_ID 					AS COD_TURNO_EXT,
	DURACXCI.SEQUENCIA 					AS NUM_PERIODO,
	CONTRATANTE.ID  					AS COD_RESPONSAVEL_EXT,
	'PRC' 								AS IDT_TPO_RESP,
	100 								AS VAL_RESPONSABILIDADE,
	TO_CHAR(INICIO,'MM')          		AS NUM_PARCELA_INI,
	TO_CHAR(FINAL,'MM')          		AS NUM_PARCELA_FIM  
FROM
  	CONTRATANTE,
  	MATRIC,
  	TURMAOFE,
  	TURMA,
  	DURACXCI,
  	CURROFE,
  	CURR,
  	CURSO,
  	RECCURSO,
  	MODALIDADE,
    PLETIVO
where  
    CURROFE.PLETIVO_ID = PLETIVO.ID
AND
  	MATRIC.STATE_ID > 3000000002001
AND
  	RECCURSO.MODALIDADE_ID = MODALIDADE.ID
AND
  	RECCURSO.CAMPUS_ID = CURROFE.CAMPUS_ID
AND
  	RECCURSO.VIGENTE = 'on'  
AND
  	RECCURSO.HABILITACAO IS NULL  
AND
  	CURSO.ID = RECCURSO.CURSO_ID
AND
  	TURMA.DURACXCI_ID = DURACXCI.ID
AND
  	TURMAOFE.TURMA_ID = TURMA.ID
AND
  	CONTRATANTE.MATRIC_ID = MATRIC.ID
and
  	MATRIC.TURMAOFE_ID = TURMAOFE.ID
AND
  	TURMAOFE.CURROFE_ID = CURROFE.ID
AND
  	CURROFE.CURR_ID = CURR.ID
AND
  	CURR.CURSO_ID = CURSO.ID
)
union 
(
SELECT
	Matric_gsCodAlunoExt(MATRIC.ID) 		AS COD_ALUNO_EXT,
	CURROFE.PLETIVO_ID 						AS COD_PERIODO_LETIVO_EXT,
	CURSO.ID 								AS COD_CURSO_EXT,
	CURSO.CODIGO||' '||DECODE(CURSO.CODIGO,'4003','Sequencial','4017','Sequencial',MODALIDADE.NOME) AS COD_HABILITACAO_EXT,
	CURROFE.CAMPUS_ID 						AS COD_CAMPUS_EXT,
	CURROFE.PERIODO_ID 						AS COD_TURNO_EXT,
	DURACXCI.SEQUENCIA 						AS NUM_PERIODO,
 	MATRIC.WPESSOA_ID  						AS COD_RESPONSAVEL_EXT,
 	'PRC' 									AS IDT_TPO_RESP,
 	100 									AS VAL_RESPONSABILIDADE,
	TO_CHAR(INICIO,'MM')  					AS NUM_PARCELA_INI,
	TO_CHAR(FINAL,'MM')   					AS NUM_PARCELA_FIM      
FROM
  	MATRIC,
  	TURMAOFE,
  	TURMA,
  	DURACXCI,
  	CURROFE,
  	CURR,
    CURSO,
  	RECCURSO,
  	MODALIDADE,
    PLETIVO
where  
  	NOT EXISTS (SELECT MATRIC_ID FROM CONTRATANTE WHERE MATRIC_ID = MATRIC.ID)
AND
    CURROFE.PLETIVO_ID = PLETIVO.ID
AND
  	MATRIC.MATRICTI_ID = 8300000000001
AND
  	MATRIC.STATE_ID > 3000000002001
AND
  	RECCURSO.MODALIDADE_ID = MODALIDADE.ID
AND
  	RECCURSO.CAMPUS_ID = CURROFE.CAMPUS_ID
AND
  	RECCURSO.VIGENTE = 'on'  
AND
  	RECCURSO.HABILITACAO IS NULL  
AND
  	CURSO.ID = RECCURSO.CURSO_ID
AND
  	TURMA.DURACXCI_ID = DURACXCI.ID
AND
  	TURMAOFE.TURMA_ID = TURMA.ID
and
  	MATRIC.TURMAOFE_ID = TURMAOFE.ID
AND
  	TURMAOFE.CURROFE_ID = CURROFE.ID
AND
  	CURROFE.CURR_ID = CURR.ID
AND
  	CURR.CURSO_ID = CURSO.ID
)
union
(
SELECT
	Matric_gsCodAlunoExt(MATRIC.ID) 			AS COD_ALUNO_EXT,
	CURROFE.PLETIVO_ID 							AS COD_PERIODO_LETIVO_EXT,
	CURSO.ID 									AS COD_CURSO_EXT,
	CURSO.CODIGO||' '||RECCURSO.HABILITACAO 	AS COD_HABILITACAO_EXT,
	CURROFE.CAMPUS_ID 							AS COD_CAMPUS_EXT,
	CURROFE.PERIODO_ID 							AS COD_TURNO_EXT,
	DURACXCI.SEQUENCIA 							AS NUM_PERIODO,
	MATRIC.WPESSOA_ID  							AS COD_RESPONSAVEL_EXT,
	'PRC' 										AS IDT_TPO_RESP,
	100 										AS VAL_RESPONSABILIDADE,
	TO_CHAR(INICIO,'MM')          				AS NUM_PARCELA_INI,
	TO_CHAR(FINAL,'MM')          				AS NUM_PARCELA_FIM        
FROM
  	MATRIC,
  	TURMAOFE,
  	TURMA,
  	DURACXCI,
  	CURROFE,
  	CURR,
  	CURSO,
  	RECCURSO,
    PLETIVO
where  
  	NOT EXISTS (SELECT MATRIC_ID FROM CONTRATANTE WHERE MATRIC_ID=MATRIC.ID)
AND
    CURROFE.PLETIVO_ID = PLETIVO.ID
AND
	TURMAOFE.TURMA_ID = TURMA.ID
AND
	MATRIC.TURMAOFE_ID = TURMAOFE.ID
AND
  	MATRIC.MATRICTI_ID = 8300000000001
AND
  	MATRIC.STATE_ID > 3000000002001
AND
  	RECCURSO.CAMPUS_ID = CURROFE.CAMPUS_ID
AND
  	RECCURSO.VIGENTE = 'on'  
AND
  	RECCURSO.HABILITACAO IS NOT NULL  
AND
  	CURSO.ID = RECCURSO.CURSO_ID
AND
  	TURMA.DURACXCI_ID = DURACXCI.ID
AND
  	TURMAOFE.CURROFE_ID = CURROFE.ID
AND
  	CURROFE.CURR_ID = CURR.ID
AND
  	CURR.CURSO_ID = CURSO.ID
)
union
(
select 
	Matric_gsCodAlunoExt(debcred.matric_origem_id) 	AS COD_ALUNO_EXT,
	CURROFE.PLETIVO_ID 								AS COD_PERIODO_LETIVO_EXT,
	CURSO.ID 									    AS COD_CURSO_EXT,
  	NULL 											AS COD_HABILITACAO_EXT,
	CURROFE.CAMPUS_ID 								AS COD_CAMPUS_EXT,
	CURROFE.PERIODO_ID 								AS COD_TURNO_EXT,
	DURACXCI.SEQUENCIA 								AS NUM_PERIODO,
	Rateio.empresa_id  								AS COD_RESPONSAVEL_EXT,
 	'VLR'        									AS IDT_TPO_RESP,
	rateio.valor 									AS VAL_RESPONSABILIDADE,
	TO_CHAR(rateiobol.data,'MM') 					AS NUM_PARCELA_INI,
	TO_CHAR(rateiobol.data,'MM') 					AS NUM_PARCELA_FIM
from 
	rateiobol, 
	rateio,
	boleto, 
	boletoitem,
	debcred,
	matric,
	turmaofe,
	currofe,
	curr,
	curso,
	duracxci,
	turma
where 
	turma.duracxci_id = duracxci.id
and
	turmaofe.turma_id = turma.id
and
	turma.duracxci_id = duracxci.id
and
	curr.curso_id = curso.id
and
	currofe.curr_id = curr.id
and
	turmaofe.currofe_id = currofe.id
and
	matric.turmaofe_id = turmaofe.id
and
	matric.id = debcred.matric_origem_id
and
	debcred.matric_origem_id is not null
and
	debcred.state_id <> 3000000016003
and
	boleto.id = debcred.boleto_destino_id
and
	boleto.id = rateiobol.boleto_orig_id 
and 
	rateio.id = rateiobol.rateio_id 
and 
	boletoitemti_id = 166600000000025 
and 
	boleto.id = boletoitem.boleto_id
)
) tabResp
ORDER BY 3 DESC