SELECT
	NULL AS COD_ACORDO_EXT,
	NULL AS NUM_RECEBIMENTO,
	NULL AS COD_TPO_RECEBIMENTO,
	NULL AS NUM_PARCELA,
	NULL AS NUM_BANCO,
	NULL AS NUM_AGENCIA,
	NULL AS NUM_CONTA,
	NULL AS NUM_CHEQUE,
	NULL AS IND_DEVOLVIDO,
	NULL AS NUM_DOC_TERCEIRO,
	NULL AS NOM_TERCEIRO,
	NULL AS NUM_AUTENTICACAO,
	NULL AS COD_BANDEIRA,
	NULL AS NUM_CARTAO,
	NULL AS VALOR
FROM
	
WHERE
