select
  WPessoa.*,
  substr(wpessoa.mensagem,1,26)                      as mensagemvest,
  WPessoa_gsrecognize ( WPessoa.Id )                 as recognize,
  Sexo_gsrecognize ( WPessoa.Sexo_Id )               as sexo,
  Cidade_gsrecognize(Cidade_Natural_Id)              as cidade_natural_id_r,
  Estado_gsrecognize(Estado_RG_Id)                   as estado,
  Escrita_gsrecognize(Escrita_Id)                    as escrita,
  Lograd_gsRecognize(Lograd_Id)                      as lograd_id_r,
  Sangue_gsRecognize(Sangue_Id)                      as Sangue,
  Ano_gsRecognize(Ano_EnsMedio_Id)                   as Ano_EnsMedio,
  WPessoa.Nome                                       as wpessoa_id_r,
  id                                                 as wpessoa_id,
  to_char(wpessoa.dtnascto,'DD-MM-YYYY')             as DtNasMk,
  to_char(wpessoa.dtnascto,'YYYY')                   as AnoNasc,
  replace((wpessoa.usuario),'_','.')                 as usuarioprof,
  replace(to_char(wpessoa.cpf/100,'000G000G000D00'),',','-')                            as cpfFormatado,
  replace(to_char(wpessoa.cpfmae/100,'000G000G000D00'),',','-')                         as cpfMaeFormatado,
  replace(to_char(wpessoa.cpfpai/100,'000G000G000D00'),',','-')                         as cpfPaiFormatado,
  substr(pis,1,3)||'.'||substr(pis,4,5)||'.'||substr(pis,9,2)||'-'||substr(pis,11,1)    as pisFormatado,
  Civil_gsrecognize(Civil_Id)                        as civil,
  lograd_gsrecognize(lograd_com_Id   )               as lograd_com_id_r,
  lograd_gsrecognize(lograd_entreg_id )              as LOGRAD_ENTREG_ID_R,
  to_char(dtnascto,'DD " de " month " de " YYYY')    as dtnascto_ext,
  Estado_gsSigla(Estado_RG_Id)                       as RGRNE_Sigla,
  ShortName(WPessoa.Nome , 30 )                      as NomeReduz,
  ShortName(WPessoa.Nome , 20 )                      as NomeReduzPeq,
  initcap(p2(nome,1))                                as nick,
  Upper(WPessoa.Nome)                                as NomeUpper,
  translate(upper(nome),'¬¡√… Õ’”‘⁄«—‹¥','AAAEEIOOOUCNU ')  as NomeCenso, 
  replace(translate(upper(mae),'¬¡√… Õ’”‘⁄«—‹¥','AAAEEIOOOUCNU '),'.','')  as MaeCenso, 
  WPessoa_gsRecognize(WPessoa_Conjuge_Id)            as WPessoa_Conjuge_Id_r,
  Lograd_gsRecognizeFormat(Lograd_Id,EnderNum)       as Endereco_Formatado,
  Lograd_gsRecognizeFormat(Lograd_Entreg_Id,EnderNumEntreg)       as EnderecoEntreg_Formatado,
  Lograd_gsRecognizeFormat(Lograd_Com_Id,EnderNumCom)       as EnderecoCom_Formatado,
  WPessoa_gnIdade(WPessoa.Id)                        as Idade,
  funcionario,
  docente,
  prestador
  
from
  WPessoa
where
  Id = nvl( p_WPessoa_Id ,0) 
