select
  LPreFolha.*,
  ShortName(GradAlu_gsRetWPessoaNome(LPreFolha.GradAlu_01_Id),27)  as WPessoa_1,
  ShortName(GradAlu_gsRetWPessoaNome(LPreFolha.GradAlu_02_Id),27)  as WPessoa_2,
  ShortName(GradAlu_gsRetWPessoaNome(LPreFolha.GradAlu_03_Id),27)  as WPessoa_3,
  ShortName(GradAlu_gsRetWPessoaNome(LPreFolha.GradAlu_04_Id),27)  as WPessoa_4,
  ShortName(GradAlu_gsRetWPessoaNome(LPreFolha.GradAlu_05_Id),27)  as WPessoa_5,
  ShortName(GradAlu_gsRetWPessoaNome(LPreFolha.GradAlu_06_Id),27)  as WPessoa_6,
  ShortName(GradAlu_gsRetWPessoaNome(LPreFolha.GradAlu_07_Id),27)  as WPessoa_7,
  ShortName(GradAlu_gsRetWPessoaNome(LPreFolha.GradAlu_08_Id),27)  as WPessoa_8,
  ShortName(GradAlu_gsRetWPessoaNome(LPreFolha.GradAlu_09_Id),27)  as WPessoa_9,
  ShortName(GradAlu_gsRetWPessoaNome(LPreFolha.GradAlu_10_Id),27)  as WPessoa_10,
  ShortName(GradAlu_gsRetWPessoaNome(LPreFolha.GradAlu_11_Id),27)  as WPessoa_11,
  ShortName(GradAlu_gsRetWPessoaNome(LPreFolha.GradAlu_12_Id),27)  as WPessoa_12,
  ShortName(GradAlu_gsRetWPessoaNome(LPreFolha.GradAlu_13_Id),27)  as WPessoa_13,
  ShortName(GradAlu_gsRetWPessoaNome(LPreFolha.GradAlu_14_Id),27)  as WPessoa_14,
  ShortName(GradAlu_gsRetWPessoaNome(LPreFolha.GradAlu_15_Id),27)  as WPessoa_15,
  ShortName(GradAlu_gsRetWPessoaNome(LPreFolha.GradAlu_16_Id),27)  as WPessoa_16,
  ShortName(GradAlu_gsRetWPessoaNome(LPreFolha.GradAlu_17_Id),27)  as WPessoa_17,
  ShortName(GradAlu_gsRetWPessoaNome(LPreFolha.GradAlu_18_Id),27)  as WPessoa_18,
  ShortName(GradAlu_gsRetWPessoaNome(LPreFolha.GradAlu_19_Id),27)  as WPessoa_19,
  ShortName(GradAlu_gsRetWPessoaNome(LPreFolha.GradAlu_20_Id),27)  as WPessoa_20,
  ShortName(GradAlu_gsRetWPessoaNome(LPreFolha.GradAlu_21_Id),27)  as WPessoa_21,
  ShortName(GradAlu_gsRetWPessoaNome(LPreFolha.GradAlu_22_Id),27)  as WPessoa_22,
  ShortName(GradAlu_gsRetWPessoaNome(LPreFolha.GradAlu_23_Id),27)  as WPessoa_23,
  ShortName(GradAlu_gsRetWPessoaNome(LPreFolha.GradAlu_24_Id),27)  as WPessoa_24,
  ShortName(GradAlu_gsRetWPessoaNome(LPreFolha.GradAlu_25_Id),27)  as WPessoa_25,
  ShortName(GradAlu_gsRetWPessoaNome(LPreFolha.GradAlu_26_Id),27)  as WPessoa_26,
  ShortName(GradAlu_gsRetWPessoaNome(LPreFolha.GradAlu_27_Id),27)  as WPessoa_27,
  ShortName(GradAlu_gsRetWPessoaNome(LPreFolha.GradAlu_28_Id),27)  as WPessoa_28,
  GradAlu_gnRetWPessoaRA(LPreFolha.GradAlu_01_Id)                  as RA_1,
  GradAlu_gnRetWPessoaRA(LPreFolha.GradAlu_02_Id)                  as RA_2,
  GradAlu_gnRetWPessoaRA(LPreFolha.GradAlu_03_Id)                  as RA_3,
  GradAlu_gnRetWPessoaRA(LPreFolha.GradAlu_04_Id)                  as RA_4,
  GradAlu_gnRetWPessoaRA(LPreFolha.GradAlu_05_Id)                  as RA_5,
  GradAlu_gnRetWPessoaRA(LPreFolha.GradAlu_06_Id)                  as RA_6,
  GradAlu_gnRetWPessoaRA(LPreFolha.GradAlu_07_Id)                  as RA_7,
  GradAlu_gnRetWPessoaRA(LPreFolha.GradAlu_08_Id)                  as RA_8,
  GradAlu_gnRetWPessoaRA(LPreFolha.GradAlu_09_Id)                  as RA_9,
  GradAlu_gnRetWPessoaRA(LPreFolha.GradAlu_10_Id)                  as RA_10,
  GradAlu_gnRetWPessoaRA(LPreFolha.GradAlu_11_Id)                  as RA_11,
  GradAlu_gnRetWPessoaRA(LPreFolha.GradAlu_12_Id)                  as RA_12,
  GradAlu_gnRetWPessoaRA(LPreFolha.GradAlu_13_Id)                  as RA_13,
  GradAlu_gnRetWPessoaRA(LPreFolha.GradAlu_14_Id)                  as RA_14,
  GradAlu_gnRetWPessoaRA(LPreFolha.GradAlu_15_Id)                  as RA_15,
  GradAlu_gnRetWPessoaRA(LPreFolha.GradAlu_16_Id)                  as RA_16,
  GradAlu_gnRetWPessoaRA(LPreFolha.GradAlu_17_Id)                  as RA_17,
  GradAlu_gnRetWPessoaRA(LPreFolha.GradAlu_18_Id)                  as RA_18,
  GradAlu_gnRetWPessoaRA(LPreFolha.GradAlu_19_Id)                  as RA_19,
  GradAlu_gnRetWPessoaRA(LPreFolha.GradAlu_20_Id)                  as RA_20,
  GradAlu_gnRetWPessoaRA(LPreFolha.GradAlu_21_Id)                  as RA_21,
  GradAlu_gnRetWPessoaRA(LPreFolha.GradAlu_22_Id)                  as RA_22,
  GradAlu_gnRetWPessoaRA(LPreFolha.GradAlu_23_Id)                  as RA_23,
  GradAlu_gnRetWPessoaRA(LPreFolha.GradAlu_24_Id)                  as RA_24,
  GradAlu_gnRetWPessoaRA(LPreFolha.GradAlu_25_Id)                  as RA_25,
  GradAlu_gnRetWPessoaRA(LPreFolha.GradAlu_26_Id)                  as RA_26,
  GradAlu_gnRetWPessoaRA(LPreFolha.GradAlu_27_Id)                  as RA_27,
  GradAlu_gnRetWPessoaRA(LPreFolha.GradAlu_28_Id)                  as RA_28,
  LPreFolha.GradAlu_01_Id as GradAlu_1_Id, 
  LPreFolha.GradAlu_02_Id as GradAlu_2_Id,
  LPreFolha.GradAlu_03_Id as GradAlu_3_Id,
  LPreFolha.GradAlu_04_Id as GradAlu_4_Id,
  LPreFolha.GradAlu_05_Id as GradAlu_5_Id,
  LPreFolha.GradAlu_06_Id as GradAlu_6_Id,
  LPreFolha.GradAlu_07_Id as GradAlu_7_Id,
  LPreFolha.GradAlu_08_Id as GradAlu_8_Id,
  LPreFolha.GradAlu_09_Id as GradAlu_9_Id,
  LPreFolha.GradAlu_10_Id,
  LPreFolha.GradAlu_11_Id,
  LPreFolha.GradAlu_12_Id,
  LPreFolha.GradAlu_13_Id,
  LPreFolha.GradAlu_14_Id,
  LPreFolha.GradAlu_15_Id,
  LPreFolha.GradAlu_16_Id,
  LPreFolha.GradAlu_17_Id,
  LPreFolha.GradAlu_18_Id,
  LPreFolha.GradAlu_19_Id,
  LPreFolha.GradAlu_20_Id,
  LPreFolha.GradAlu_21_Id,
  LPreFolha.GradAlu_22_Id,
  LPreFolha.GradAlu_23_Id,
  LPreFolha.GradAlu_24_Id,
  LPreFolha.GradAlu_25_Id,
  LPreFolha.GradAlu_26_Id,
  LPreFolha.GradAlu_27_Id,
  LPreFolha.GradAlu_28_Id  
from
  LPreFolha
where
  LPreFolha.Id = nvl( p_LPreFolha_Id ,0)
